name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/image-diff/visual-testing-cypress.cy.js
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports
          run: ls -R