name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: 'Raptor_Git_Actions'
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Running test on BrowserStack'
        run:  BROWSERSTACK_LOCAL=true browserstack-cypress run --sync
      - name: Download visual screenshots
        uses: actions/upload-artifact@v3
        with:
          name: actions-visual-report
          path: cypress-visual-screenshots
      - name: Download visual report
        uses: actions/upload-artifact@v3
        with:
          name: actions-visual-report
          path: cypress-visual-html-report