name: Cypress Tests on Electron

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Install Node.js and your project dependencies (including Cypress)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use your project's node version
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # 2. Run the Cypress tests, specifying only the electron browser
      - name: Run Cypress Tests on Electron
        run: npx cypress run --browser electron

      # 3. Upload the reports from the correct paths
      - name: Upload Visual Report
        uses: actions/upload-artifact@v4
        with:
          name: visual-report-electron
          path: cypress-visual-report/

      - name: Upload Visual Diffs (on failure)
        # This step only runs if the previous test step failed
        if: failure() 
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs-electron
          path: cypress-visual-screenshots/diff/